spring.application.name=Assignment1
#Allow ongoing requests to completed
server.shutdown = graceful
#Max num of Tomcat request-processing threads.
server.tomcat.threads.max=200

#Minimum number of threads kept ready to handle incoming requests.
#Avoids the overhead of creating new threads when traffic arrives
server.tomcat.threads.min-spare=20

#Max num of incoming connections that can wait in accept queue 
#when all request-processing threads are busy.
server.tomcat.accept-count=200



#Max time for each shutdown phase is 20 seconds
spring.lifecycle.timeout-per-shutdown-phase=20s
#Max time allowed for asynchronous MVC request to remain in progress
spring.mvc.async.request-timeout=4800

#Controls logging levels to keep useful logs while preventing sensitive headers from being logged
logging.level.root = INFO
logging.level.org.springframework.web.reactive.function.client = INFO
logging.level.reactor.netty.http.client = INFO
 
